### PR TITLE
Add option to skip failure  if no tests were found

### PR DESCRIPTION
**Pull request by tahirmt**
Adds an option to not fail the check if there are no test results. This can be if the file was not found or if there are actually no tests.

### CODE REVIEW

**Comment by tahirmt** [comment]
Not sure why the lock file changed but adding that in because it did

**Review by vikramatscore — DISMISSED** [review]
Looks good, but it seems that `lockFileVersion` can get affected by the build environment. What **npm** version do you have installed?

**Comment by tahirmt** [comment]
@vikramatscore 6.14.7. I can discard that change if that makes more sense?

**Comment by poldz123** [comment]
@tahirmt I don't think you added any libraries right? let's undo the package.lock

**Comment by tahirmt** [comment]
Yeah I didn't change any libraries. Just the script. I'll revert that

**Comment by tahirmt** [comment]
@poldz123 @vikramatscore reverted the `package-lock.json` change

**Review by poldz123 — APPROVED** [review]
LGTM! Thanks for improving this @tahirmt

**Comment by tahirmt** [comment]
@poldz123 I was also thinking instead of annotations on GitHub, maybe we could post a review on the PR since GitHub only allows a limited number of annotations.

**Comment by poldz123** [comment]
@tahirmt I think we are trying to prevent polluting PRs with comments. This is where annotations come in handy since it is not part of your PR but is isolated into a different page.

Though there is a limit on it :(

**Comment by tahirmt** [comment]
At least they shouldn't 😇

**Comment by tahirmt** [comment]
Oh yeah and it already has this feature I just added

**Review by ketenshi — APPROVED** [review]
👍

**Review by ketenshi — APPROVED** [review]

**Review by alexsm20 — APPROVED** [review]

**Review by GlobakMaxim — APPROVED** [review]

**Review by vkondrav — APPROVED** [review]

**Pull request merged**
