### PR TITLE
Added ability to comment in PR with the link to the job

### PR DESCRIPTION
**Pull request by poldz123**
This will create a comment within your PR if it exists with a link to the failed unit tests and also automatically removes them when unit tests return successfully.

## Sample Comment
Capture

### CODE REVIEW

**Review by vkondrav — COMMENTED** [review]
what's the change to `index.js` I can't even see because it says "too large"

**Comment by poldz123** [comment]
> what's the change to `index.js` I can't even see because it says "too large"

No need to worry about index.js, it is the package version of the changes.

**Review by vkondrav — APPROVED** [review]

**Review by vikramatscore — APPROVED** [review]

**Comment by tahirmt** [comment]
@poldz123 should we push this upstream? Maybe with a boolean option to enable/disable it

**Comment by poldz123** [comment]
@tahirmt This is only valid if your workflow is using `pull_request` not comment will be pushed when you are using `push` event

**Comment by tahirmt** [comment]
> @tahirmt This is only valid if your workflow is using `pull_request` no comment will be pushed when you are using `push` event

I meant should we create a pull request on the original repo?

**Comment by poldz123** [comment]
@tahirmt Ahh, I don't think we need to create a pull-request on the original repo, also that repo is already deprecated.

**Comment by tahirmt** [comment]
Oh yeah and the replacement already has the feature from #2

**Pull request merged**
